# Generated by Django 5.2.13 on 2026-04-30 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArquivoImportado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_arquivo_original", models.CharField(max_length=255)),
                ("nome_arquivo_atual", models.CharField(max_length=255)),
                ("caminho_arquivo", models.CharField(max_length=500)),
                ("hash_arquivo", models.CharField(max_length=64, unique=True)),
                ("data_detectada", models.DateTimeField(auto_now_add=True)),
                ("data_importacao", models.DateTimeField(blank=True, null=True)),
                (
                    "status_importacao",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("em_processamento", "Em processamento"),
                            ("sucesso", "Sucesso"),
                            ("falha", "Falha"),
                            ("ignorado", "Ignorado"),
                        ],
                        default="pendente",
                        max_length=20,
                    ),
                ),
                ("mensagem_erro", models.TextField(blank=True, default="")),
                ("texto_extraido", models.TextField(blank=True, default="")),
                ("quantidade_paginas", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Arquivo importado",
                "verbose_name_plural": "Arquivos importados",
                "ordering": ["-data_detectada"],
            },
        ),
        migrations.CreateModel(
            name="LogImportacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("etapa", models.CharField(max_length=80)),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("debug", "Debug"),
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                        ],
                        default="info",
                        max_length=10,
                    ),
                ),
                ("mensagem", models.TextField()),
                ("data_hora", models.DateTimeField(auto_now_add=True)),
                (
                    "arquivo_relacionado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="importacao.arquivoimportado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de importação",
                "verbose_name_plural": "Logs de importação",
                "ordering": ["-data_hora"],
            },
        ),
    ]
