# Generated by Django 5.2.13 on 2026-04-30 02:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ResultadoMegaSena",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("concurso", models.PositiveIntegerField(unique=True)),
                ("data_apuracao", models.DateField()),
                ("dezena_1", models.PositiveSmallIntegerField()),
                ("dezena_2", models.PositiveSmallIntegerField()),
                ("dezena_3", models.PositiveSmallIntegerField()),
                ("dezena_4", models.PositiveSmallIntegerField()),
                ("dezena_5", models.PositiveSmallIntegerField()),
                ("dezena_6", models.PositiveSmallIntegerField()),
            ],
            options={
                "verbose_name": "Resultado Mega-Sena",
                "verbose_name_plural": "Resultados Mega-Sena",
                "ordering": ["-concurso"],
            },
        ),
    ]
