# Generated by Django 5.2.13 on 2026-04-30 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("importacao", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoJogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=80, unique=True)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Tipo de jogo",
                "verbose_name_plural": "Tipos de jogo",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Comprovante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_jogo", models.DateField(blank=True, null=True)),
                (
                    "valor_total_aposta",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "codigo_autenticacao",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("observacoes", models.TextField(blank=True, default="")),
                (
                    "arquivo_importado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comprovantes",
                        to="importacao.arquivoimportado",
                    ),
                ),
                (
                    "tipo_jogo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comprovantes",
                        to="apostas.tipojogo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comprovante",
                "verbose_name_plural": "Comprovantes",
                "ordering": ["-data_jogo", "id"],
            },
        ),
        migrations.CreateModel(
            name="Aposta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequencia", models.PositiveIntegerField(default=1)),
                ("descricao", models.CharField(blank=True, default="", max_length=120)),
                (
                    "valor_aposta",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "comprovante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apostas",
                        to="apostas.comprovante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aposta",
                "verbose_name_plural": "Apostas",
                "ordering": ["comprovante_id", "sequencia"],
            },
        ),
        migrations.CreateModel(
            name="NumeroApostado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordem", models.PositiveSmallIntegerField()),
                ("numero", models.PositiveSmallIntegerField()),
                (
                    "aposta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="numeros",
                        to="apostas.aposta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Número apostado",
                "verbose_name_plural": "Números apostados",
                "ordering": ["aposta_id", "ordem"],
                "indexes": [
                    models.Index(
                        fields=["numero"], name="apostas_num_numero_037f32_idx"
                    )
                ],
                "unique_together": {("aposta", "ordem")},
            },
        ),
    ]
