# Generated by Django 5.2.13 on 2026-04-30 02:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apostas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aposta",
            name="concurso",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
